### ISSUE TITLE
[Apple M1/Asahi Linux] <jemalloc>: Unsupported system page size

### ISSUE THREAD

**Issue by paisuhas** [FEX-Emu/FEX#1650]
Hello, I'm running into the following error when FEX is built and run on Asahi Linux:

```
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
terminate called without an active exception
Aborted
```

Is there a know workaround or fix?

**Comment by Sonicadvance1** [comment]
Not yet

**Comment by marcan** [comment]
FEX is unlikely to run on Asahi standard kernels for the foreseeable future. We will provide 4K kernels where it works once support for that has matured on the kernel side, for users who want to use FEX.

**Comment by stalkerg** [comment]
Can somebody explain more why FEX can't support 16k pages?

**Comment by marcan** [comment]
FEX cannot generally support 16K pages with its current design because x86 uses 4K pages and full VM emulation to emulate 4K on 16K is prohibitively expensive.

FEX can partially support 16K pages with tricks to allow many/most apps to run, and that is #1921.

There is one realistic option for native 4K page support: run FEX in a VM. That could work on top of a full guest Linux kernel (with filesystem and as-yet-nonexistent GPU UAPI-level passthrough you could get it close to behaving like the guest is part of the host environment without *too* much effort), or with some hypothetical thin shim to directly run FEX apps as KVM processes using some kind of not-really-a-hypervisor layer to thunk guest syscalls to the host. You'd still have to play a bunch of VM games to map things around, but it would work with an unmodified host kernel. How viable that second option is I'll leave to the FEX people to decide.

**Comment by liberodark** [comment]
I hope fex add support on asahi thank your great work.

**Comment by kotleni** [comment]
The developers of ASAHI Linux wrote on the blog that they will soon force it to work: D (Asahi Lina on Stream showed the work of Steam+Some Games)

🌮

**Comment by neobrain** [comment]
In an effort to tidy up the issue tracker, we're tracking non-4K efforts in https://github.com/FEX-Emu/FEX/issues/1921.

**Comment by xiangzhai** [comment]
Hi,

To an end-user, muvm (libkrun), binfmt-dispatcher and FEXInterpreter made x86/x86_64 programs can be run transparently.
But just curious, to a developer, how to build the FEX rpm packages for Asahi Linux? how to debug jemalloc for Unsupported system page size? I guess just build them on 4K pagesize Linux distributions for AArch64?

Thanks,
Leslie Zhai

**Comment by alyssarosenzweig** [comment]
`muvm`
