### ISSUE TITLE
4k page emulation

### ISSUE THREAD

**Issue by skmp** [FEX-Emu/FEX#1921]
Splitting from #1221 

from @skmp 
> We now have a fairly clean interface - one would need to add support for this in virtual void `GuestMmap(void *addr, size_t length, int prot, int flags, int fd, off_t offset) = 0;` and `GuestMunmap`, and maybe introduce a `GuestMprotect` and then it would all work.

from @marcan 
> mmap on files can be made to work perfectly fine as long as the vaddr is not requested as fixed. You just align the mapping to 16K and give the app an offset halfway into the page if needed. munmap would then align back before unmapping the 16K aligned block.

> mprotect similarly would only fail if the app is trying to do its own page management at page granularity. Many uses of mprotect are used on whatever mmap returned, and since that would be 16K aligned (or the above hack for file maps), it could similarly be made to work.

We are already tracking guest VMAs for mtrack, so adding the few extra things needed should be fairly uneventful.

I'm putting it in the 2212 milestone, hopefully the asahi side is ready by then.

**Comment by alyssarosenzweig** [comment]
On the Asahi side, we're pursuing microVMs as the solution here, rather than betting on hacks in FEX. There's not a lot of enthusiasm for this on the FEX side, given it will never work as a general solution and would be challenging technically. Closing as "not planned", as the relevant use cases are better served by krun (for now?).
