### ISSUE TITLE
How to use AOTIR in right way ? 

### ISSUE THREAD

**Issue by baikaishiuc** [FEX-Emu/FEX#2291]
Hi

I write a simple hello.c to test AOTIR. 

```
#include <stdio.h>
#include <stdlib.h>


int main()
{
    puts("hello, world!");
    puts("hello, hello, hello  ");
    return 0;
}
```

When I want to use AOTIR feature, 

1. change ~/.fex-emu/Config.json:AOTIRCapture to 1. 
2. run prog:
```
~/source/FEX/build-Release-Thunk/Bin/FEXLoader -- ./hello
```
to generate aotir file in ~/.fex-emu/aotir/ directory,  
3. change AOTIRCatpure back to 0, AOTIRLoad to 1, 
4. run above command again, now it will use aotir feature 

**First Question:**
Have a simple way to use this feature ?  I dont want to change config file again and again. 

If i set both AOTIRCapture and AOTIRLoad to 1, then FEX crashed in a null pointer deference.

**Second Question:**
```
bogus@bogus:~/source/test/hello$ ~/source/FEX/build-Release-Thunk/Bin/FEXLoader -- ./hello
try to open file: /home/bogus/.fex-emu/aotir/ld.so.cache-16224829478350186670-sTlP.aotir 
try to open file: /home/bogus/.fex-emu/aotir/libc.so.6-15624069436683325548-sTlP.aotir 
hello, world!
hello, hello, hello  
```
I found the FEX not use hello-*.aotir, why ?

**Third Question:**
what is aotir format? I drag the file into Ghidra , it seems not be recognized.

**Comment by Sonicadvance1** [comment]
Since the feature is currently incomplete, it is expected to use `AOTIRCapture` on one run and then `AOTIRLoad` on additional runs. It isn't fully tested with both enabled at one time; As you can see, it crashes with both enabled.

> I found the FEX not use hello-*.aotir, why ?

This is a bug in the FEXLoader frontend where it fails to load the first ELF's IR cache loaded in. Not well tested so it was missed.

> what is aotir format? I drag the file into Ghidra , it seems not be recognized.

This is a custom file format, the only documentation on it is currently the source. Because it is an incomplete feature.

**Comment by baikaishiuc** [comment]
> 

ok, thank you . I try to read the source code
