### ISSUE TITLE
can't dlopen: libFEXCore.so: cannot allocate memory in static TLS block

### ISSUE THREAD

**Issue by AndreRH** [FEX-Emu/FEX#2565]
Hi,
I'd like to use libFEXCore in Hangover ( https://github.com/AndreRH/hangover/ ), but a major blocker is that I can't dlopen it.
The message "libFEXCore.so: cannot allocate memory in static TLS block" seems to indicate that the library want's to use more TLS memory than statically available, but even if I (for testing purposes) remove all thread_locals from libFEXCore, I get the same message. Any idea?

Note that using LD_PRELOAD works for a test application, but won't be viable for Hangover/Wine

**Comment by Sonicadvance1** [comment]
Looks like this is caused by jemalloc using an initial-exec TLS type.
As you've found out, even though we provide a libFEXCore.so, it isn't tested in our CI (Since the ELF loader currently uses the static linked object). This is a hole in the CI that FEX should work on fixing since we will want to ensure not to break shared library users. Just hasn't been high on the priority list since other burning fires have had higher priority.

As a temporary workaround, patching our jemalloc source as follows will get dlopen working.
```diff
diff --git a/pregen/include/jemalloc/internal/jemalloc_internal_defs.h b/pregen/include/jemalloc/internal/jemalloc_internal_defs.h
index 2e259795..d42ff6e5 100644
--- a/pregen/include/jemalloc/internal/jemalloc_internal_defs.h
+++ b/pregen/include/jemalloc/internal/jemalloc_internal_defs.h
@@ -137,7 +137,7 @@
 /* #undef JEMALLOC_MUTEX_INIT_CB */

 /* Non-empty if the tls_model attribute is supported. */
-#define JEMALLOC_TLS_MODEL __attribute__((tls_model("initial-exec")))
+#define JEMALLOC_TLS_MODEL

 /*
  * JEMALLOC_DEBUG enables assertions and other sanity checks, and disables
  ```

**Comment by AndreRH** [comment]
this fixes that particular issue, thanks!
