### ISSUE TITLE
ARM machine-  run x86_64 libraries

### ISSUE THREAD

**Issue by victoriastraberg** [FEX-Emu/FEX#2644]
Hi! @phire @1ace @skmp @baikaishiuc @philpax 
I want to install Qemu on my Arm machine (Ubuntu 22, Linux 4.4, Rock4SE Radxa https://wiki.radxa.com/Rock4/se ) and get access to run libraries so.files in x86_64. Is your FEX a great solution for me? Im new to this. Thanks in advance! :)

**Comment by Sonicadvance1** [comment]
QEmu and FEX-Emu have slightly overlapping use cases so depending on what you want to do it may or may not be a good fit. QEmu supports both system emulation and "user" emulation, where FEX-Emu only supports "user" emulation.

This means that QEmu can boot a full operating system and linux kernel with its system emulation. FEX-Emu on the other hand only does usermode emulation. Which means you can execute something like Steam and x86 applications directly in your ARM64 operating system.

So really it just depends on what you're trying to accomplish.

**Comment by Sonicadvance1** [comment]
FEX can likely work for this case then. Once FEX is setup it should be as simple as executing the application using `FEXInterpreter` or directly. Although I would recommend building your project for ARM directly.

As for why the PPA failed to install, this is usually due to outdated or broken packages on your system. You can try installing the PPA manually from the sourc: https://launchpad.net/~fex-emu/+archive/ubuntu/fex Then rerunning the script should finish up the setup.

**Comment by victoriastraberg** [comment]
sudo add-apt-repository ppa:fex-emu/fex
sudo apt update

Ok! I tried this above and it did not work.. I still get the PPA failed to install.. @Sonicadvance1 strange?

**Comment by Sonicadvance1** [comment]
Very strange. I don't know what would cause this to fail other than a broken package manager on the device.

**Comment by neobrain** [comment]
Closing since there hasn't been any activity and there doesn't seem to be an underlying general problem with FEX here.
