### ISSUE TITLE
The Witcher 3 slow block

### ISSUE THREAD

**Issue by Sonicadvance1** [FEX-Emu/FEX#2688]
![Image_2023-05-22_20-44-23](https://github.com/FEX-Emu/FEX/assets/1018829/d836405c-10d0-44b8-95f9-a323a51f8702)
![Image_2023-05-22_20-44-35](https://github.com/FEX-Emu/FEX/assets/1018829/97f08c51-35c9-4f72-98d1-8769a0ad8a6e)
![Image_2023-05-22_20-44-41](https://github.com/FEX-Emu/FEX/assets/1018829/812e4b7c-3bb9-4473-9b32-416cef739e97)
Will populate this with more documentation in the future.

**Comment by dougallj** [comment]
Interesting! While the block is dominated by flag calculcations (for `add rdx, rcx`, from `CalculcateFlags_ADD`), I don't think that's the issue. My first clue was that the following block will also have flag calculcations (for `cmp rax, rcx`), and will execute at least as many times as this block.

It looks like you're using a sampling profiler, and it's pointing squarely at the instruction immediately after the `ldaddal`. So I'd say the issue is with the `ldaddal`: a slow atomic operation, presumably either because of the hardware implementation, or because of software issues leading to contention. While it's not my area of expertise, the translation of the atomic instruction looks fine, so I doubt there's much FEX can do to this block to improve performance?

**Comment by Sonicadvance1** [comment]
Indeed, the `lock xadd` instruction translates to the `ldaddal` semantically so that part can't really be improved. I haven't looked too closely at this one but since it gets executed a /lot/ over the period of about a minute, just getting the converted code to a more ideal size should help significantly regardless. Which will end up being multiple optimizations stacked on top of each other.

**Comment by Sonicadvance1** [comment]
Also looked in to why its startup time is now absolute garbage.
Turns out Xess has some function that is generating a 261,432 byte frame on the stack one byte at a time. This causes our RA's `CalculateNodeInterference` to absolutely explode in CPU time at startup.

Example attached of part of the function that is executed at startup. I would need to scroll for minutes to cover it all.
https://github.com/FEX-Emu/FEX/assets/1018829/6fedd138-1f00-4b31-9f54-a2de9a829dfc

**Comment by Sonicadvance1** [comment]
```asm
%ifdef CONFIG
{
  "MemoryRegions": {
    "0x200000000": "0x20000"
  }
}
%endif

mov rsp, 0x200000000
%assign i 0
%rep 0x10000
mov byte [rsp + (0x10000 + i)], (0x01 + (i << 2)) & 0xFF
%assign i i+1
%endrep

hlt
```

This assembly test can reproduce the issue. It seems RA performance is exacerbated by huge live ranges due to constant pooling. Restricting the constant pooling ranges with a heuristic Seems to work around the Xess issue at least.
