### ISSUE TITLE
Optimize PF calculation

### ISSUE THREAD

**Issue by Sonicadvance1** [FEX-Emu/FEX#2707]
The PF calculation is very spicy and isn't generating optimal codegen.

Current codegen:
```asm
   0x00000002a10ed054:  and     x24, x22, #0xff
   0x00000002a10ed058:  fmov    d0, x24
   0x00000002a10ed05c:  cnt     v0.8b, v0.8b
   0x00000002a10ed060:  addv    b0, v0.8b
   0x00000002a10ed064:  umov    w24, v0.b[0]
   0x00000002a10ed068:  eor     x24, x24, #0x1
   0x00000002a10ed06c:  ubfx    x24, x24, #0, #1
   0x00000002a10ed070:  strb    w24, [x28, #706]
   ```
What it can be:
```asm
   0x00000002a10ed064:  movi    v1.8b, #1
   0x00000002a10ed058:  fmov    s0, w22
   0x00000002a10ed05c:  cnt     v0.8b, v0.8b
   0x00000002a10ed068:  bic     v0.8b, v1.8b, v0.8b
   0x00000002a10ed070:  str     b0, [x28, #706]
   ```
   
Not a significant reduction in instructions, but removes a FPR->GPR move which is quite an improvement.

For CPUs with CSSC extension this can be even more optimal but even the upcoming X4/A720/A520 doesn't support them.

llvm-mca results:
Before:
```
Iterations:        100
Instructions:      800
Total Cycles:      315
Total uOps:        1000

Dispatch Width:    10
uOps Per Cycle:    3.17
IPC:               2.54
Block RThroughput: 3.0
```

After:
```
Iterations:        100
Instructions:      500
Total Cycles:      408
Total uOps:        600

Dispatch Width:    10
uOps Per Cycle:    1.47
IPC:               1.23
Block RThroughput: 3.0
```

**Comment by dougallj** [comment]
That `BIC` should be an `AND`, right?

I'm personally partial to the variant:

```
    movi    v1.8b, #0
    fmov    s0, w22
    cnt     v0.8b, v0.8b
    sli     v0.8b, v1.8b, #1
    str     b0, [x28, #706]
```

Because `movi v1.8b, #0` can be handled by the renamer on Apple CPUs, that saves a SIMD uop. (Though the SLI may be more expensive than the AND on other microarchitectures, so YMMV. And PF flag calculations probably aren't happening in SIMD-uop bound code anyway?)

(And I'm not sure if you're already do this, but deferring this to read-time is probably desirable. The extreme is just storing the byte without `CNT`, though there's a middle-ground of just skipping the `AND`, since it's probably free to ignore the high bits in many use-cases.)

**Comment by Sonicadvance1** [comment]
In the example we're taking advantage of the BIC's bitwise negation to flip the bits returned from the popcount. Effectively doing the eor and ubfx in one operation from what we currently do.

As for only storing the byte and calculating on read. That's an interesting idea and is likely a good optimization since in most cases we're only calculating PF when we leave the block's visibility where we didn't already optimize out the PF calculation. So a combination of both would be good!

**Comment by dougallj** [comment]
Oh, right, yeah, that's really nice! (My mistake, I had the PF flag backwards, so my SLI suggestion is nonsense.)

**Comment by alyssarosenzweig** [comment]
With #2804 merged, PF calculation is now deferred, leaving only a single `eor` op, so I think this is done.
