### ISSUE TITLE
FEX page size requirement

### ISSUE THREAD

**Issue by ChanthMiao** [FEX-Emu/FEX#2730]
## Problem

I am trying to port FEX in a alpha like architecture, which is 8k pagesize only.

It seems that FEX requires 4k pagesize. I implement MemAllocator8k and MemAllocator8k32Bit to handle guest memory syscall.

Currently, the biggest question for me is that what compements of FEXt self , except the guest syscall handler, depends on 4k pagesize.

**Comment by Sonicadvance1** [comment]
FEX itself outside of the allocators make only a few 4K pagesize assumptions, this is because implementing x86 emulation on any platform that doesn't support 4k pagesizes is always going to be a hack.
While we're trying to remove most 4k pagesize assumptions for our Wine support, there is probably still some missing depending on where you look.

**Comment by ChanthMiao** [comment]
It seems that the `FEXCore::Allocator`  requires 4k pagesize?

**Comment by ChanthMiao** [comment]
@Sonicadvance1 
Do you know the pagesize requirements of `OSAllocator_64Bit` and `ForwardOnlyIntrusiveArenaAllocator`?
Is it safe to modify them to work in a 8k pagesize platform?

**Comment by neobrain** [comment]
Development discussion is best done on FEX's Discord.

For 4K page size emulation, see https://github.com/FEX-Emu/FEX/issues/1921 .
