### ISSUE TITLE
sched_getaffinity is broken

### ISSUE THREAD

**Issue by skmp** [FEX-Emu/FEX#329]

**Comment by Sonicadvance1** [comment]
Still broken?
Was worked on with #109, #330, and #331

**Comment by Sonicadvance1** [comment]
This is no longer broken. We just don't honour a guest application's request for getting and setting afinity.
We can't allow it either since a lot of applications choose a core either randomly or at the low end of the index scale, slapping these cores on to little CPU cores and running like garbage.
