### ISSUE TITLE
Unsupported system page size segfault

### ISSUE THREAD

**Issue by Heinrich-XIAO** [FEX-Emu/FEX#3496]
**The Bug**
When I run the FEXBash command at all, it just outputs this
\<jemalloc>: Unsupported system page size
\<jemalloc>: Unsupported system page size
zsh: segmentation fault (core dumped)  FEXBash

**What machine I'm on**
OS: Fedora Linux Asahi Remix 39 (Thirty Nine) aarch64
Host: Apple MacBook Air (M1, 2020)
Kernel: 6.6.3-413.asahi.fc39.aarch64+16k

**Comment by Sonicadvance1** [comment]
This is because FEX only supports 4kb page size systems.
Fedora Asahi Remix uses a 16kb page size kernel.
FEX isn't going to support 4kb page size emulation, see more at https://github.com/FEX-Emu/FEX/issues/1921

To get FEX running on Asahi and 16kb page size systems you will need to use their forthcoming microVM solution. Which you can see more about here https://sinrega.org/2023-10-06-using-microvms-for-gaming-on-fedora-asahi/

**Comment by Spidy123222** [comment]
> This is because FEX only supports 4kb page size systems. Fedora Asahi Remix uses a 16kb page size kernel. FEX isn't going to support 4kb page size emulation, see more at #1921
> 
> To get FEX running on Asahi and 16kb page size systems you will need to use their forthcoming microVM solution. Which you can see more about here https://sinrega.org/2023-10-06-using-microvms-for-gaming-on-fedora-asahi/

The microvm setup won’t work at the current asahi Linux version. The developer of the microvm won’t allow people to use it until it’s upstream in asahi Linux. https://fosstodon.org/@slp/111941799627294252

So it’s just the waiting game which could take a while possibly, not sure.
