### ISSUE TITLE
Darwinia Linux bugs

### ISSUE THREAD

**Issue by Sonicadvance1** [FEX-Emu/FEX#3662]
Darwinia doing incorrect chdir with proc/self?

Seems to break the game from Lina's stream. Needs some poking.

**Comment by tycho** [comment]
The texture "sprites/virii.bmp" does exist though?

(I agree the null pointer checks should probably be there, but at the same time, that should *never* fail if it's loading archives properly because there's no rational circumstance that the texture would be missing, so it'd just be a `DarwiniaReleaseAssert(!=nullptr)` anyway.)

**Comment by Sonicadvance1** [comment]
> The texture "sprites/virii.bmp" does exist though?
> 
> (I agree the null pointer checks should probably be there, but at the same time, that should _never_ fail if it's loading archives properly because there's no rational circumstance that the texture would be missing, so it'd just be a `DarwiniaReleaseAssert(!=nullptr)` anyway.)

That's where the mystery lies. I assume it's checking some filesystem path first and then falling back to some memory mapped file (If I'm reading the assembly and the strace correctly).

```
191678 1644226 newfstatat(AT_FDCWD, "data/sprites/viriifull.bmp", 0xffffeefa95a0, 0) = -1 ENOENT (No such file or directory)
191679 1644226 newfstatat(AT_FDCWD, "data/sprites/virii.bmp", 0xffffeefa95a0, 0) = -1 ENOENT (No such file or directory)
191680 1644226 --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=NULL} ---
```

So then the question then comes down to _why_ is this `Resource::GetBinaryReader` returning nullptr under emulation.
I haven't yet dove in to the details of the assembly yet since it's doing some sort of map(vector?) lookup and it's relatively complex. Initial inspection looks like it always allocates some memory on the heap and only returns nullptr in a couple of edge-case conditions.

Hopefully not some mimalloc quirk or brk thing, but maybe FEX is somehow managing to mess up that lookup somehow.

**Comment by tycho** [comment]
Yeah, it checks filesystem first, because anything under `<game dir>/data` takes precedence.

The archives and their contents are all decompressed and loaded into system memory at game startup, and the file blobs are stored in an `ankerl::unordered_dense::map<std::string, MemoryMappedFile *>` [1]. The key is a std::string of the path (e.g. `data/sprites/virii.bmp`) and the `MemoryMappedFile` is effectively just a pointer to some heap allocated memory and a length.

If the logic in `ankerl::unordered_dense::map` is breaking under emulation that'd certainly account for the null pointers.

[1] Note: the nomenclature of `MemoryMappedFile` is wrong, it's actually just heap allocated rather than truly "memory mapped", but I haven't renamed it because it didn't matter too much.

**Comment by tycho** [comment]
Also if you want to just test whether your fstat/fstatx fix works without dealing with the complexity of the in-memory archive data, you could extract the .dat files. They're either plain tar (sounds) or tar+zstd (everything else). Then you can delete the .dat files and it'll grab everything from the data subdir.

**Comment by Sonicadvance1** [comment]
Oh, that's really good to know. I'll need to test extracting those and see if it changes behaviour.

**Comment by Sonicadvance1** [comment]
Looks like this is now breaking due to optimization passes. Seems to be a combination of constprop and the dead flag calculation elimination. Nailing down exactly what is breaking is more difficult.

**Comment by Sonicadvance1** [comment]
Looks like if I disable constprop on LOADMEMTSO and STOREMEMTSO then the crash goes away. So something odd going on there.

**Comment by Sonicadvance1** [comment]
This is now fixed. Thanks for the insights!

**Comment by tycho** [comment]
> This is now fixed. Thanks for the insights!

What was the solution with the optimization passes?

**Comment by alyssarosenzweig** [comment]
https://github.com/FEX-Emu/FEX/pull/3669

**Comment by Sonicadvance1** [comment]
Two bugs we encountered in #3669, silly bugs on our end.

First bug was SIB addressing would sometimes transpose the base and offset register, so `[rax + rbx * 2]` turned in to `[rbx + rax * 2]`, fairly rare bug but it bit us here.

Second bug was our const prop pass was trying to smash SIB addressing modes in to vector loadstores that ARM literally can't support. This took the form of an instruction asserting in our JIT `pmovzxbq xmm5, word [rbx+r15+0x3d4]` from `HUF_readDTableX1_wksp`. ARM can't encode that complex of an address in one instruction and it was breaking things.

New unit tests to ensure we test both of these cases to ensure we don't break it in the future. Both were edge-case behaviours that either didn't get hit in other games, or at least didn't break any we found.
