### ISSUE TITLE
Unclear FexConfig setting

### ISSUE THREAD

**Issue by misterjdrg** [FEX-Emu/FEX#3698]
What `FexConfig`'s  `Hacks` -> `TSO Enable` do?
Does it means 'Your cpu supports TSO' or 'TSO emulation' ?

**Comment by Sonicadvance1** [comment]
The option when checked means that TSO emulation is enabled. There is no indication inside of FEXConfig if your CPU supports native TSO (like Apple Silicon).

There is also no indication as for /how/ TSO emulation occurs, since FEX supports multiple ways to emulate TSO:

1. Atomics (The slowest and worst option)
2. LRCPC1/2/3 (The better option)
3. Hardware TSO (The best option and only available on Apple Silicon)

**Comment by misterjdrg** [comment]
Thanks, can you add `emulation`word to setting name in FexConfig?
`TSO Enabled` -> `TSO emulation Enabled`
`TSO sub-options` -> `TSO emulation sub-options`
