### ISSUE TITLE
SSE4a

### ISSUE THREAD

**Issue by Torinde** [FEX-Emu/FEX#3838]
- [ ] EXTRQ/​INSERTQ Combined mask-shift instructions.
- [ ] MOVNTSD/​MOVNTSS Scalar streaming store instructions.

Header is [<ammintrin.h>](https://gcc.gnu.org/git/?p=gcc.git;a=blob;f=gcc/config/i386/ammintrin.h;h=b94731a9e2ca64529189a3ed8b16a5147c27c652;hb=HEAD)

**Comment by Sonicadvance1** [comment]
Do you have a reason for wanting SSE4a to be implemented? As far as I'm aware, nothing requires support for it because it was short lived and AMD has removed the extension from their own CPUs.
We have also already implemented the scalar non-temporal stores, since I implemented them on accident.

As for EXTRQ and INSERTQ, there's no good algorithm to implement these as far as I can tell in ARM and I would prefer not to implement them if it's nasty to support. But if you have some ideas for implementing them then maybe.

**Comment by alyssarosenzweig** [comment]
Closing unless a real use case is identified.

**Comment by squidbus** [comment]
I'm not sure if this is within your scope, but consoles like the PS4 have games that require SSE4a, so direct translation of these instructions to an ARM implementation could be useful for running them more efficiently in emulators.

**Comment by Sonicadvance1** [comment]
Those PS4 emulators should add an ARM64 JIT instead. Stacking emulators is not a good idea, SSE4a is the least of your worries there.

**Comment by squidbus** [comment]
> Those PS4 emulators should add an ARM64 JIT instead. Stacking emulators is not a good idea, SSE4a is the least of your worries there.

Well... ideally they would be able to use something like FEXCore *as* an ARM64 JIT as an x86_64 JIT is a massive undertaking. But again I can understand why this might be out of your scope.

**Comment by Sonicadvance1** [comment]
SSE4a has been added, although we don't expose the CPUID by default because it's now just there purely for compatibility.
