### ISSUE TITLE
FMA4

### ISSUE THREAD

**Issue by Torinde** [FEX-Emu/FEX#3839]
[GCC header](https://gcc.gnu.org/git/?p=gcc.git;a=blob;f=gcc/config/i386/fma4intrin.h;h=23d36b9f5fa586a536b1b90d57c179e85f72d2cd;hb=HEAD)
[llvm header](https://github.com/llvm/llvm-project/blob/4998587e6f5f66d464ac22ad4c11fe9afd2d56ab/clang/lib/Headers/fma4intrin.h)

**Comment by Sonicadvance1** [comment]
Same question for FMA4 as SSE4a. Do you have a reason for wanting this implemented? AMD has also removed support for FMA4 in their CPUs already. I doubt anything hardcodes a requirement for FMA4.

As for implementation details, theoretically this wouldn't be very hard; We already model FMA3 as FMA4 IR operations inside of FEX. We just need to add unit tests, implement support for XOP decoding, and handle them. Since AMD removed the instructions from their CPUs, we obviously can't have the unittests running on our x86 runner, which is kind of frustrating.

**Comment by alyssarosenzweig** [comment]
I'm generally opposed to supporting things that actual contemporary hardware doesn't, sounds like a recipe for bad times...

**Comment by alyssarosenzweig** [comment]
Closing this as wontfix unless there's a real use case identified.
