### ISSUE TITLE
Investigate: GOG installer fails

### ISSUE THREAD

**Issue by Sonicadvance1** [FEX-Emu/FEX#678]
Haven't checked this in a few months. Might be fine now.
Needs checked first

**Comment by phire** [comment]
Installer appears to work now; Successfully installed "Beneath a Steal Sky", "Duke Nukem 3D Atomic Edition". The Strellaris installer was also working until I ran out of disk space.

Only works in text mode when running on an arm64 host, which I assume is due to a lack of gtk libraries in the rootfs.

**Comment by phire** [comment]
Tested on x86 host with no rootfs. GUI version of the installer works too.
