### ISSUE TITLE
-T with more than 1 breaks a lot of things

### ISSUE THREAD

**Issue by Sonicadvance1** [FEX-Emu/FEX#680]
dav1d is a good test for this.

**Comment by Sonicadvance1** [comment]
radeon GPU also breaks this all over the place

**Comment by phire** [comment]
dav1d appears to not be a great test. It breaks (see #767), it ignores it's own error then it deadlocks. 

I can't confirm that the deadlock wouldn't happen on native if you injected the exact same breakage.

**Comment by phire** [comment]
Geekbench is pretty good at locking up during one of it's multi-core benchmarks, looks like it's failing to force it's test threads to join. Not the same one every time. Sometimes it won't deadlock at all.

But not a great reproduction because we have to sit though all the single-core tests first (though maybe if we bought a geekbench license, we could jump straight to a test that is known to break reliably)

**Comment by phire** [comment]
So with some tracing in strace and gdb, it appears the issue is somehow related to `pthread_cond_broadcast`, which looks like it's stuck on a futex waiting for the first waiter to the corresponding `pthread_cond_wait` to notify it back. For some reason (is `pthread_cond_wait` messing up an atomic add/sub/swap? I would think we would be seeing much more wide-spread issues if so) none of the signaled threads appear to be notifying the signalling thread back. They all move onto the next pthread_cond_wait and sit there waiting for a signal that will never come. 

I did try making my own [pthread example](https://gist.github.com/phire/747760d4438cb225d958044e584c6948) that looked kind of like geekbench's syscalls, but I couldn't reproduce this bug. 

I'm going to put this on hold for now and work on other issues.

Future plans:

 * [ ] build a debug version of libpthreads, check exactly where we are failing. 
 * [ ] See if we can find a better reproduction for this bug, something small, standalone and either open source, or easy to RE.
 * [ ] RE a reproduced to see exactly what the pthread_cond workflow is. 
 * [ ] check out glib's mutex tests. They are apparently failing and might be failing for this exact reason.

**Comment by Sonicadvance1** [comment]
For the glibc test `LD_LIBRARY_PATH=./:./nptl/ ./elf/ld.so ./nptl/tst-cond16 && echo $?`
Then of course have those passed to FEX correctly.

**Comment by Sonicadvance1** [comment]
./nptl/tst-cond16, tst-cond17 will hang
And maybe ./nptl/tst-rwlock9 might not work as well.

**Comment by phire** [comment]
Geekbench seems much improved over before. But I did manage to encounter two failures while doing test runs. 

My very first run failed, and the 4th run failed, but beyond that it's proving very hard to reproduce. 

When I did examine the crashes I did encounter, they appeared to have slightly slightly different symptoms than before.
